# SERVICE for MYSQL DB
apiVersion: v1
kind: Service
metadata:
      name: mysql-svc
      labels:
        name: mysql-pod
        app: db
spec:
    type: ClusterIP
    ports:
    - port: 3306
      targetPort: 3306
    selector:
       name: mysql-pod
       app:  db