# Deployment for MYSQL DB
apiVersion: apps/v1
kind: Deployment
metadata:
     name: mysql-deploy
     labels:
       name: mysql-pod
       app: db
spec:
   replicas: 3
   selector:
      matchLabels:
        name: mysql-pod
        app: db
   template:
        metadata:
          name: mysql-pod
          labels:
             name: mysql-pod
             app: db
        spec:
          containers:
           - name:  mysql
             image: mysql:5.7
             env:
             - name: MYSQL_PASSWORD
               valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user-password
             - name: MYSQL_USER
               valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
             - name: MYSQL_ROOT_PASSWORD
               valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
             envFrom:
             - configMapRef:
                name: db-config
             volumeMounts:
              - mountPath: "/var/lib/mysql"
                name: db-storage
             ports:
              - containerPort: 3306
          volumes:
            - name: db-storage
              persistentVolumeClaim:
                claimName: db-pvc